services:
    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Corrige el volumen si es incorrecto
        depends_on:
            - laravel.test
        networks:
            - sail
            - boda-app_sail  # Agregamos esta red para que pueda comunicarse con Laravel

    laravel.test:
        build:
            context: 'docker/8.2'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.2/app'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
            - boda-app_sail  # Agregamos esta red

networks:
    sail:
        driver: bridge
    boda-app_sail:
        external: true  # Mantiene la red externa para compatibilidad
